# Generated by Django 3.2.6 on 2021-09-28 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Required', max_length=255, null=True, verbose_name='Transaction Id')),
                ('payment_method', models.CharField(blank=True, help_text='Not Required', max_length=255, null=True, verbose_name='Payment Method')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, help_text='Total Tax Charged For Order', max_digits=7, null=True, verbose_name='Tax')),
                ('shipping_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Total Shipping Charge For Order', max_digits=7, null=True, verbose_name='Shipping Charge')),
                ('is_paid', models.BooleanField(default=False, help_text='Is Order Amount Paid By User', verbose_name='Order Amount Paid Status')),
                ('is_delivered', models.BooleanField(default=False, help_text='Is Order Delivered To User', verbose_name='Order Delivery Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Order Amount Paid At Timestamp')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Order Delivered At Timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Order Created At Timestamp')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Not Required', max_length=255, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='count_in_stock',
            field=models.IntegerField(blank=True, default=0, help_text='Total Number Of Product in Stock', null=True, verbose_name='Product Count In Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='num_reviews',
            field=models.IntegerField(blank=True, default=0, help_text='Total Number Of Product Reviews', null=True, verbose_name='Number Of Reviews'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product Rating', max_digits=7, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, help_text='Required', max_digits=7, verbose_name='Discount Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, help_text='Required', max_digits=7, verbose_name='Regular Price'),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Required', max_length=255, verbose_name='Shipping Address')),
                ('city', models.CharField(help_text='Required', max_length=255, verbose_name='City Name')),
                ('state', models.CharField(help_text='Required', max_length=255, verbose_name='State Name')),
                ('zipcode', models.CharField(help_text='Required', max_length=255, verbose_name='Postal Code')),
                ('country', models.CharField(help_text='Required', max_length=255, verbose_name='Country Name')),
                ('shipping_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Total Shipping Charge For Order', max_digits=7, null=True, verbose_name='Shipping Charge')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Shipping Address Created At Timestamp')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Address',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Not Required', max_length=255, null=True, verbose_name='User Name')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Product Rating', max_digits=7, null=True, verbose_name='Rating')),
                ('comment', models.TextField(blank=True, help_text='Not Required', null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Review Created At Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Review Updated At Timestamp')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_creator', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, help_text='Total Quantity Of Order Item', null=True, verbose_name='Quantity Of Order Item')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Order Item Created At Timestamp')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ('created_at',),
            },
        ),
    ]
