# Generated by Django 3.2.6 on 2021-10-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210928_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(blank=True, help_text='Not Required', max_length=255, null=True, verbose_name='Customer Name'),
        ),
    ]
